"""Add ledger_id to import_jobs

Revision ID: 0002_add_ledger_id_to_import_jobs
Revises: 0001_initial
Create Date: 2026-06-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_add_ledger_id_to_import_jobs'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('ledger_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_import_jobs_ledgers', 'import_jobs', 'ledgers', ['ledger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_import_jobs_ledgers', 'import_jobs', type_='foreignkey')
    op.drop_column('import_jobs', 'ledger_id')
    # ### end Alembic commands ###
