"""add economic event workorder

Revision ID: 0034
Revises: 0033_ops_missing_indexes
Create Date: 2026-08-01 17:40:16.299214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0034'
down_revision: Union[str, None] = '0033_ops_missing_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_no', sa.String(length=80), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('display_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'import', 'agent')", name='ck_economic_event_source_valid'),
    sa.CheckConstraint("status IN ('draft', 'collecting', 'pending_review', 'pending_post', 'posted', 'closed', 'failed', 'cancelled')", name='ck_economic_event_status_valid'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_events_event_no'), 'economic_events', ['event_no'], unique=True)
    op.create_index(op.f('ix_economic_events_ledger_id'), 'economic_events', ['ledger_id'], unique=False)
    op.create_index('ix_economic_events_ledger_status', 'economic_events', ['ledger_id', 'status'], unique=False)
    op.create_table('economic_event_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(length=80), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('api_name', sa.String(length=200), nullable=True),
    sa.Column('payload_digest', sa.String(length=128), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['economic_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_event_steps_event_id'), 'economic_event_steps', ['event_id'], unique=False)
    op.create_index('ix_economic_event_steps_event_id_seq', 'economic_event_steps', ['event_id', 'sequence'], unique=False)
    op.create_table('economic_event_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['economic_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'source_file_id', name='uq_event_file')
    )
    op.create_index(op.f('ix_economic_event_files_event_id'), 'economic_event_files', ['event_id'], unique=False)
    op.create_index(op.f('ix_economic_event_files_source_file_id'), 'economic_event_files', ['source_file_id'], unique=False)
    op.create_table('economic_event_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('accounting_entry_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accounting_entry_id'], ['accounting_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['economic_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'accounting_entry_id', name='uq_event_entry')
    )
    op.create_index(op.f('ix_economic_event_entries_accounting_entry_id'), 'economic_event_entries', ['accounting_entry_id'], unique=False)
    op.create_index(op.f('ix_economic_event_entries_event_id'), 'economic_event_entries', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_of_accounts', sa.Column('organization_id', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_chart_of_accounts_code'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_accounting_entries_ledger_voucher'), 'accounting_entries', ['ledger_id', 'voucher_date', 'voucher_no'], unique=False)
    op.create_index(op.f('ix_accounting_entries_ledger_review'), 'accounting_entries', ['ledger_id', 'review_status'], unique=False)
    op.create_index(op.f('ix_accounting_entries_ledger_date'), 'accounting_entries', ['ledger_id', 'voucher_date'], unique=False)
    op.create_table('global_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('settings_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('settings_value', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_settings_settings_key'), 'global_settings', ['settings_key'], unique=1)
    op.drop_index(op.f('ix_economic_event_entries_event_id'), table_name='economic_event_entries')
    op.drop_index(op.f('ix_economic_event_entries_accounting_entry_id'), table_name='economic_event_entries')
    op.drop_table('economic_event_entries')
    op.drop_index(op.f('ix_economic_event_files_source_file_id'), table_name='economic_event_files')
    op.drop_index(op.f('ix_economic_event_files_event_id'), table_name='economic_event_files')
    op.drop_table('economic_event_files')
    op.drop_index('ix_economic_event_steps_event_id_seq', table_name='economic_event_steps')
    op.drop_index(op.f('ix_economic_event_steps_event_id'), table_name='economic_event_steps')
    op.drop_table('economic_event_steps')
    op.drop_index('ix_economic_events_ledger_status', table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_ledger_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_event_no'), table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###
